apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hpa-example
spec:
    replicas: 1
    template:
        metadata:
            name: hpa-example
            labels:
                app: hpa-example
        spec:
            containers:
            - name: hpa-example
              image: danibachar/app:latest_new_test
              ports:
              - name: http-port
                containerPort: 8081
              resources:
                  requests:
                      cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
    name: hpa-example-svc
spec:
    type: LoadBalancer
    selector:
        app: hpa-example
    ports:
    - port: 31001
      nodePort: 31001
      targetPort: http-port
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-example-autoscaler
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: hpa-example
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 50
