swagger: '2.0'
info:
  title: Test
  description: Test
  version: '1.0.0'
  contact:
    name: API Support
    email: daniel@lnstechnologies.com
host: api.lnstechnologies.com
x-google-endpoints:
    - name: api.lnstechnologies.com
      allowCors: true
basePath: /v1
consumes:
  - application/json
  - application/x-www-form-urlencoded
schemes:
  - http
produces:
  - application/json
  - application/x-www-form-urlencoded
paths:
  /load:
    get:
      description: load
      security: []
      operationId: load
      produces:
        - application/json
        - application/x-www-form-urlencoded
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      responses:
        200:
          description: Good
          schema:
            $ref: '#/definitions/tmpResponseSuccess'
        400:
          description: Bad
          schema:
            $ref: '#/definitions/generalResponseError'
definitions:
  generalResponseError:
    type: object
    description: Error object with error string
    properties:
      message:
        type: string
  tmpResponseSuccess:
    type: object
    description: tmp for swagger deploy
    properties:
      message:
        type: string
