kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  labels:
    environment: dev
    tier: backend
    component: app-server
data:
  useCloudLogging: "true"
  prettifyJson: "false"
  namespace: "dev"
  debugMode: "true"
