apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-microsvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-microsvc
        microservice: app
        environment: dev
        tier: backend
        component: app-server
    spec:
      containers:
      - image: danibachar/app:local
        name: app-microsvc-cont
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: PRETTIFY_JSON
          valueFrom:
            configMapKeyRef:
              name: config
              key: prettifyJson
        resources:
          requests:
            cpu: "0.15"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 4
