apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
  labels:
    microservice: app
    environment: dev
    tier: backend
    component: app-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: app
